server:
  allowed_domains:
    - '{{APP_TLD}}'
    - 'localhost'
  name: jitsu
  auth: '${env.CONFIGURATOR_ADMIN_TOKEN|demo___please_provide_value_in_production___}'

storage:
  redis:
    host: '${env.REDIS_URL}'
    tls_skip_verify: '${env.TLS_SKIP_VERIFY|false}'

jitsu:
  base_url: '${env.JITSU_SERVER_URL|}'
  admin_token: '${env.SERVER_ADMIN_TOKEN|demo___please_provide_value_in_production___}'

auth:
  redis:
    host: '${env.REDIS_URL}'
    tls_skip_verify: '${env.TLS_SKIP_VERIFY|false}'
    access_secret: '${env.UI_AUTH_ACCESS_SECRET|demo___please_provide_value_in_production___}'
    refresh_secret: '${env.UI_AUTH_REFRESH_SECRET|demo___please_provide_value_in_production___}'