server:
  name: jitsu
  disable_welcome_page: true
  strict_auth_tokens: true
  admin_token: '${env.SERVER_ADMIN_TOKEN|demo___please_provide_value_in_production___}'
  telemetry: '${env.JITSU_CONFIGURATOR_URL}/api/v1/telemetry?token=${env.CONFIGURATOR_ADMIN_TOKEN|demo___please_provide_value_in_production___}'

geo:
  maxmind_path: '${env.MAX_MIND_PATH|}'

geo_resolvers: '${env.JITSU_CONFIGURATOR_URL}/api/v1/geo_data_resolvers?token=${env.CONFIGURATOR_ADMIN_TOKEN|demo___please_provide_value_in_production___}'

api_keys: '${env.JITSU_CONFIGURATOR_URL}/api/v1/apikeys?token=${env.CONFIGURATOR_ADMIN_TOKEN|demo___please_provide_value_in_production___}'

destinations: '${env.JITSU_CONFIGURATOR_URL}/api/v1/destinations?token=${env.CONFIGURATOR_ADMIN_TOKEN|demo___please_provide_value_in_production___}'

sources: '${env.JITSU_CONFIGURATOR_URL}/api/v1/sources?token=${env.CONFIGURATOR_ADMIN_TOKEN|demo___please_provide_value_in_production___}'

system: '${env.JITSU_CONFIGURATOR_URL}/api/v1/system/configuration'

notifications:
  slack:
    url: '${env.SLACK_NOTIFICATIONS_WEBHOOK|}'

users_recognition:
  enabled: '${env.USER_RECOGNITION_ENABLED|true}'

meta:
  storage:
    redis:
      host: '${env.REDIS_URL}'
      tls_skip_verify: '${env.TLS_SKIP_VERIFY|false}'

coordination:
  type: redis

sql_debug_log:
  ddl:
    path: /home/eventnative/data/logs
    rotation_min: 1440
  queries:
    path: /home/eventnative/data/logs
    rotation_min: 60

google-ads:
  developer-token: '${env.GOOGLE_ADS_DEVELOPER_TOKEN|}'
